# Generated by Django 5.1.5 on 2025-02-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', help_text='Enter the book language (e.g. English, Farsi, etc.)', max_length=20),
        ),
    ]
